// flow-typed signature: 5e9d6844e45d8e5e0b9340bd33d3229b
// flow-typed version: <<STUB>>/eslint-config-rung_v^2.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-rung'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-rung' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-rung/index' {
  declare module.exports: $Exports<'eslint-config-rung'>;
}
declare module 'eslint-config-rung/index.js' {
  declare module.exports: $Exports<'eslint-config-rung'>;
}
